### ISSUE TITLE
Consider having just one empty line between each section in CSS.

### ISSUE THREAD

**Issue by josephtkim** [jeneenedickert/Tea-Cozy#2]
Instead of separating each section by 2 empty lines, it is usually best practice to use just a single empty line. 
https://github.com/jeneenedickert/Tea-Cozy/blob/master/css/style.css#L2-L14

```css
body {
  margin: 0;
  font-family: "Helvetica", sans-serif;
  color: seashell;
  background-color: black;
  font-size: 22px;
  text-align: center;
}

a {
  color: seashell;
}
```
